version: '3.8'
services:
  php:
    image: repox/laravel-dev-php:8.0
    container_name: app
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/docker-vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: db
    links:
      - php
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/bind.cnf
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: rootpass
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 85:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: rootpass
    networks:
      - app-network
  composer:
    image: repox/laravel-dev-php:8.0
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['/usr/bin/composer']  
  artisan:
    image: repox/laravel-dev-php:8.0
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
# #Volumes>
volumes:
  dbdata:
    driver: local